# Generated by Django 4.2.16 on 2026-06-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role_assumption', models.IntegerField()),
                ('production_emphasis', models.IntegerField()),
                ('initiation_of_structure', models.IntegerField()),
                ('tolerance_of_uncertainty', models.IntegerField()),
                ('integration', models.IntegerField()),
                ('consideration', models.IntegerField()),
                ('country', models.CharField(max_length=3)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('education_level', models.CharField(max_length=20)),
                ('work_experience_years', models.FloatField()),
                ('position_level', models.CharField(max_length=10)),
                ('predicted_class', models.IntegerField()),
                ('predicted_class_name', models.CharField(max_length=50)),
                ('probabilities', models.JSONField()),
                ('top3_shap_features', models.JSONField()),
                ('all_shap_values', models.JSONField()),
                ('counterfactual', models.JSONField(blank=True, null=True)),
                ('recommendations', models.JSONField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
