# Generated by Django 4.2.16 on 2026-07-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='target_leadership_style',
            field=models.CharField(blank=True, choices=[('Transformational', 'Transformational'), ('Transactional', 'Transactional'), ('Supportive', 'Supportive'), ('Laissez-Faire', 'Laissez-Faire')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='education_level',
            field=models.CharField(choices=[('Bachelor', 'Bachelor'), ('Master', 'Master'), ('PhD', 'PhD'), ('High School', 'High School')], default='Bachelor', max_length=20),
        ),
    ]
